### ISSUE TITLE
C# files in the obj/ folder should be considered Auto-Generated.

### ISSUE THREAD

**Issue by otac0n** [DotNetAnalyzers/StyleCopAnalyzers#1430]
This is standard practice for auto-generated code.

**Comment by sharwell** [comment]
All standard code generators which place code in this folder have one of two behaviors:

1. The output file is empty.
2. The output file contains an `<auto-generated` or `<autogenerated` comment at the top of the file.

In either case, the file is automatically excluded from analysis. If you are running into a case where a file is not excluded, can you include information about the tool used to generate the file along with the version of the tool in use?

**Comment by otac0n** [comment]
This is an enforced AssemblyInfo tool, it generates a pair of AssemblyInfo.cs files, which are marked with `<copyright...` rather than `<auto-generated`.

**Comment by sharwell** [comment]
If you are not able to update the tool to produce the correct file, you should be able to modify the approach I added in #1479 to correct the output of this tool after the file is generated.

**Comment by otac0n** [comment]
Even though I have a work around, I discovered how to override the
template, I still maintain that the `obj/` folder is the very definition of
"generated code" and should be treated as such.

**Comment by sharwell** [comment]
The **obj** folder name is the default, but it can be renamed. Only convention prevents you from placing normal source files there. To the maximum extent possible, we want to avoid using file names and/or paths to identify generated code.

**Comment by otac0n** [comment]
Could we add an MsBuild `<GeneratedCode Inlcude="WhateverYouNeed" />` or something less ugly?

**Comment by sharwell** [comment]
:memo: See #1479 for further discussion related to the detection of auto generated code.

**Comment by sharwell** [comment]
I'm moving this back for now to whatever release follows 1.0 (Stable).

**Comment by yaakov-h** [comment]
What about project items that are marked with `<AutoGen>True</AutoGen>` in the project file?

**Comment by sharwell** [comment]
@yaakov-h That's roughly the same as #726. Currently analyzers do not have access to this information, so there's not much we can do.

**Comment by jkanczler** [comment]
sharwell, we're using a custom code generator for example. Of course I can easily change the code generator to generate the <auto-generated/> tag, but I think it's not a flexible solution by the StyleCop analyzer. As a tool it should support multiple excluding mechanism as Microsoft's Code Analysis supports multiple solutions as well. As for the record Microsoft's CodeAnalysis can understand the System.CodeDom.Compiler.GeneratedCodeAttribute too. ;-)

So in the old StyleCop there was an option to add exclude patterns, like exclude *.generated.cs files. I liked that very much, we implemented our code generator to generate all the files with those post fix.

**Comment by sharwell** [comment]
@jkanczler See #1094 regarding `GeneratedCodeAttribute`.

**Comment by sharwell** [comment]
Considering dotnet/roslyn#3705 will likely be implemented for Update 2 (Roslyn 1.2), I'm thinking we can defer to that rather than implement something here and have it change later.

**Comment by sharwell** [comment]
Starting with 1.1 Beta 1, generated files (detection and exclusion) are handled entirely by Roslyn itself.

**Comment by MisinformedDNA** [comment]
What detection and exclusion are you referring to? I just added the GeneratedCode attribute to my class and I'm still getting SA issues from that class. Adding `// <auto-generated></auto-generated>` does, however, work.

**Comment by sharwell** [comment]
> What detection and exclusion are you referring to?

Starting with the 1.1 releases, StyleCop Analyzers tells Roslyn "I do not want to report diagnostics in generated code". Roslyn is then responsible for identifying all generating code and preventing warnings from appearing there. For any situation where code generated code is not being treated as generated code, it's either a bug in Roslyn or a bug in the tool that generated the code. I am happy to help narrow things down (feel free even to file a new issue here if you aren't sure where the problem is) and in some cases we've worked directly with tool authors to fix the issue.
